### ISSUE TITLE
2.27 example values

### ISSUE THREAD

**Issue by dzbyr** [cbourke/ComputerScienceI#13]
I read this amazing book's chapter 2 and implemented examples.

I need to check whether my code work correct or not when implementing 2.27th example.

Could you add an output of this example's below.

https://demonstrations.wolfram.com/AreasOfTheLensAndTwoLunesOfTwoIntersectingCircles/

I can share make easier this https://github.com/dzbyr/c_codes here my code for try.

I got A=0.599951 for  r=1, d=2.44, R=2. 

At least Could you add these result to textbook for check immediately whether correct code or not for time saving.

**Comment by cbourke** [comment]
The area I got was 0.615814 for your input parameters of 1, 2, and d = 2.44

**Comment by dzbyr** [comment]
Sorry for late answer. The calculation same I think.
Since I wanted the field looks to be ~0.6, I changed the distance to 2.45, and the difference originated from there. 
This %+1 change caused total error. Sorry for the point I missed 
I undo the values r=1, d=2.44,R=2 then got 0.615814.
