### ISSUE TITLE
Broken link on Youtube video

### ISSUE THREAD

**Issue by ghost** [cbourke/ComputerScienceI#15]
I am watching [this video on debugging with gdb](https://www.youtube.com/watch?v=bWH-nL7v5F4) and when I click on the link with the files for the demonstration, it takes me here: https://github.com/cbourke/ComputerScienceI/tree/master/hacks/hack9.0-files, which doesn't exist. I'm assuming the link should be [going here](https://github.com/cbourke/ComputerScienceI/tree/master/hacks/hack-debugging)?

**Comment by cbourke** [comment]
Updated YT page a while ago, thanks.
