### ISSUE TITLE
Syllabus Clarification

### ISSUE THREAD

**Issue by hbiede** [cbourke/ComputerScienceI#2]
For the sake of labs, in 156, there was confusion on whether or not partial credit was possible between some LAs. I believe this should be clarified in the syllabus to replace "Labs not completed on time _may not_ receive full credit" so as to include an explicit declaration of the possibility of partial points.

**Comment by cbourke** [comment]
I've added emphasis, but even with emphasis the word "may" leaves it open for us to play with.  GTAs/LAs are initially given instructions NOT to allow partial credit starting out to establish good habits.  If something goes wrong or there is a particular issue they have the freedom to make exceptions using their own good judgement.
