### ISSUE TITLE
TA guidelines for hours

### ISSUE THREAD

**Issue by hbiede** [cbourke/ComputerScienceI#3]
The GTA specifications on the TALA document (under "General Responsibilities") state "Holding regular office hours (at least 2 per week) in a designated area," while the LA section does not include the hour requirement. Assuming you have a minimum as you did for 156, specifying that in this section could be advantageous for the new LAs

**Comment by cbourke** [comment]
This is yet to be determined.  The GTA policy is department-wide.  We've been thinking of 5 hours per week with at least 2 on Friday and/or Monday evenings, but that is not yet finalized.

**Comment by cbourke** [comment]
Closing the issue as cleanup.  LA office hour policies may also be under the full or partial purview of the LA program.
